import '../extensions_services.dart';
import 'package:karee/core.dart';
import '/app/controllers/payment_controller.dart';

/// Generated by Karee 

extension PaymentControllerExtension on PaymentController {
	static late final PaymentController? service;
	static bool loaded = false;
	void init(){
		omApi = readConfig('@{api.om}');
		mtnApi = readConfig('@{api.mtn}');
		PaymentControllerExtension.service = this;
		PaymentControllerExtension.loaded = true;
		paymentService = serviceExtensions['PaymentService']();
	}
	PaymentController get self {
		init();
		return this;
	}
}

PaymentController get $extendedPaymentController {
	if(!PaymentControllerExtension.loaded){
		PaymentController().self;
	}	return PaymentControllerExtension.service!;
}