import '/app/services/payment_service.dart';

/// Generated by Karee

extension PaymentServiceExtension on PaymentService {
  static late final PaymentService? service;
  static bool loaded = false;
  void init() {
    PaymentServiceExtension.service = this;
    PaymentServiceExtension.loaded = true;
  }

  PaymentService get self {
    init();
    return this;
  }
}

PaymentService $extendedPaymentService() {
  if (!PaymentServiceExtension.loaded) {
    PaymentService().self;
  }
  return PaymentServiceExtension.service!;
}
